# Generated by Django 4.1.5 on 2023-01-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0003_alter_node_parent_menu_alter_node_parent_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='display_name',
            field=models.CharField(default='to_change', max_length=40, verbose_name='Display name'),
            preserve_default=False,
        ),
    ]
