# Generated by Django 4.1.5 on 2023-01-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0005_alter_node_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='named_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Named URL'),
        ),
        migrations.AlterField(
            model_name='node',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL (used by default)'),
        ),
    ]
