# Generated by Django 4.1.5 on 2023-01-06 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0006_node_named_url_alter_node_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='parent_node',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='node',
            name='parent_menu',
        ),
        migrations.AddField(
            model_name='node',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='tree_menu.menu'),
        ),
    ]
