# Generated by Django 4.1.5 on 2023-01-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0007_rename_parent_node_node_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='named_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Named URL (used by default)'),
        ),
        migrations.AlterField(
            model_name='node',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
    ]
