# Generated by Django 4.1.5 on 2023-01-07 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0008_alter_node_named_url_alter_node_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='root_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_root_node', to='tree_menu.node'),
        ),
    ]
